val spaces_lead                   : Str.regexp
val spaces_trail                  : Str.regexp
val white_spaces                  : Str.regexp
val white_spaces_and_newlines     : Str.regexp
val newline                       : Str.regexp
val top_from                      : Str.regexp
val header_tag                    : Str.regexp
val header_data                   : Str.regexp
val angle_bracket_open_lead       : Str.regexp
val angle_bracket_close_trail     : Str.regexp
val between_angle_bracketed_items : Str.regexp
val comma                         : Str.regexp
